### PR TITLE
Move 1 7

### PR DESCRIPTION
**Pull request by simonsnow**
help!

### CODE REVIEW

**Review by mentor-tara — APPROVED** [review]
### You're good. No mines hit. Merge this PR to continue the game.

This is the current status:

|   | **A** | **B** | **C** | **D** | **E** | **F** | **G** | **H** |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **1** |   |   |   |   | :pirate_flag: | :pirate_flag: |   |   |
| **2** |   |   |   | :pirate_flag: | :pirate_flag: |   |   |   |
| **3** |   |   |   |   | :pirate_flag: |   |   |   |
| **4** |   |   | 3 | 3 | 1 | 1 |   |   |
| **5** |   |   | :pirate_flag: | 1 | 0 | 1 |   | 1 |
| **6** |   |   | :pirate_flag: | 1 | 0 | 1 | 1 | 1 |
| **7** |   |   |   | 1 | 0 | 0 | 0 | 0 |
| **8** |   |   |   | 1 | 0 | 0 | 0 | 0 |

Mines remaining: 3
Moves made: 10[](clear-E5)

**Review by mentor-tara — APPROVED** [review]
### You're good. No mines hit. Merge this PR to continue the game.

This is the current status:

|   | **A** | **B** | **C** | **D** | **E** | **F** | **G** | **H** |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **1** |   |   |   |   | :pirate_flag: | :pirate_flag: |   |   |
| **2** |   |   |   | :pirate_flag: | :pirate_flag: |   |   |   |
| **3** |   |   |   |   | :pirate_flag: |   |   |   |
| **4** |   |   | 3 | 3 | 1 | 1 |   |   |
| **5** |   |   | :pirate_flag: | 1 | 0 | 1 |   | 1 |
| **6** |   |   |   | 1 | 0 | 1 | 1 | 1 |
| **7** |   |   |   | 1 | 0 | 0 | 0 | 0 |
| **8** |   |   |   | 1 | 0 | 0 | 0 | 0 |

Mines remaining: 4
Moves made: 9[](clear-E5)

**Review by mentor-tara — APPROVED** [review]
### You're good. No mines hit. Merge this PR to continue the game.

This is the current status:

|   | **A** | **B** | **C** | **D** | **E** | **F** | **G** | **H** |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **1** |   |   |   |   | :pirate_flag: | :pirate_flag: |   |   |
| **2** |   |   |   | :pirate_flag: | :pirate_flag: |   |   |   |
| **3** |   |   |   |   | :pirate_flag: |   |   |   |
| **4** |   |   | 3 | 3 | 1 | 1 |   |   |
| **5** |   |   | :pirate_flag: | 1 | 0 | 1 | :pirate_flag: | 1 |
| **6** |   |   |   | 1 | 0 | 1 | 1 | 1 |
| **7** |   |   |   | 1 | 0 | 0 | 0 | 0 |
| **8** |   |   |   | 1 | 0 | 0 | 0 | 0 |

Mines remaining: 3
Moves made: 10[](flag-G5)

**Review by mentor-tara — APPROVED** [review]
### You're good. No mines hit. Merge this PR to continue the game.

This is the current status:

|   | **A** | **B** | **C** | **D** | **E** | **F** | **G** | **H** |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **1** |   |   |   |   | :pirate_flag: | :pirate_flag: |   |   |
| **2** |   |   |   | :pirate_flag: | :pirate_flag: |   |   |   |
| **3** |   |   |   |   | :pirate_flag: |   |   |   |
| **4** |   |   | 3 | 3 | 1 | 1 |   |   |
| **5** |   |   | :pirate_flag: | 1 | 0 | 1 | :pirate_flag: | 1 |
| **6** |   |   |   | 1 | 0 | 1 | 1 | 1 |
| **7** |   |   |   | 1 | 0 | 0 | 0 | 0 |
| **8** |   |   |   | 1 | 0 | 0 | 0 | 0 |

Mines remaining: 3
Moves made: 10[](clear-F7)

**Comment by mentor-tara** [comment]
### You lost! Unfortunately you didn't flag all the mines correctly :slightly_frowning_face:

This is the current board:

|   | **A** | **B** | **C** | **D** | **E** | **F** | **G** | **H** |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **1** |   |   |   |   | :pirate_flag: | :pirate_flag: |   |   |
| **2** |   |   |   | :pirate_flag: | :pirate_flag: |   |   |   |
| **3** |   |   |   |   | :pirate_flag: |   |   |   |
| **4** |   |   | 3 | 3 | 1 | 1 |   |   |
| **5** |   |   | :pirate_flag: | 1 | 0 | 1 | :pirate_flag: | 1 |
| **6** |   |   |   | 1 | 0 | 1 | 1 | 1 |
| **7** |   |   |   | 1 | 0 | 0 | 0 | 0 |
| **8** |   |   |   | 1 | 0 | 0 | 0 | 0 |

And this is the revealed board:

|   | **A** | **B** | **C** | **D** | **E** | **F** | **G** | **H** |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| **1** | 0 | 0 | 0 | 2 | :bomb: | :bomb: | 1 | 0 |
| **2** | 0 | 1 | 2 | 4 | :bomb: | 3 | 1 | 0 |
| **3** | 0 | 1 | :bomb: | :bomb: | 2 | 1 | 0 | 0 |
| **4** | 0 | 2 | 3 | 3 | 1 | 1 | 1 | 1 |
| **5** | 1 | 2 | :bomb: | 1 | 0 | 1 | :bomb: | 1 |
| **6** | :bomb: | 3 | 2 | 1 | 0 | 1 | 1 | 1 |
| **7** | 2 | :bomb: | 2 | 1 | 0 | 0 | 0 | 0 |
| **8** | 1 | 2 | :bomb: | 1 | 0 | 0 | 0 | 0 |

---

### This game is over but I created a PR so you can start a new game. You can close this PR.[](end)

**Comment by simonsnow** [comment]
I was misunderstanding the board representation. Next time will be better.

**Pull request closed without merging**
